/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DemoRequestService } from "../demoRequest.service";
import { DemoRequestCreateInput } from "./DemoRequestCreateInput";
import { DemoRequest } from "./DemoRequest";
import { DemoRequestFindManyArgs } from "./DemoRequestFindManyArgs";
import { DemoRequestWhereUniqueInput } from "./DemoRequestWhereUniqueInput";
import { DemoRequestUpdateInput } from "./DemoRequestUpdateInput";

export class DemoRequestControllerBase {
  constructor(protected readonly service: DemoRequestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DemoRequest })
  async createDemoRequest(
    @common.Body() data: DemoRequestCreateInput
  ): Promise<DemoRequest> {
    return await this.service.createDemoRequest({
      data: data,
      select: {
        company: true,
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        phone: true,
        preferredTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DemoRequest] })
  @ApiNestedQuery(DemoRequestFindManyArgs)
  async demoRequests(@common.Req() request: Request): Promise<DemoRequest[]> {
    const args = plainToClass(DemoRequestFindManyArgs, request.query);
    return this.service.demoRequests({
      ...args,
      select: {
        company: true,
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        phone: true,
        preferredTime: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DemoRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async demoRequest(
    @common.Param() params: DemoRequestWhereUniqueInput
  ): Promise<DemoRequest | null> {
    const result = await this.service.demoRequest({
      where: params,
      select: {
        company: true,
        createdAt: true,
        email: true,
        id: true,
        message: true,
        name: true,
        phone: true,
        preferredTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DemoRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDemoRequest(
    @common.Param() params: DemoRequestWhereUniqueInput,
    @common.Body() data: DemoRequestUpdateInput
  ): Promise<DemoRequest | null> {
    try {
      return await this.service.updateDemoRequest({
        where: params,
        data: data,
        select: {
          company: true,
          createdAt: true,
          email: true,
          id: true,
          message: true,
          name: true,
          phone: true,
          preferredTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DemoRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDemoRequest(
    @common.Param() params: DemoRequestWhereUniqueInput
  ): Promise<DemoRequest | null> {
    try {
      return await this.service.deleteDemoRequest({
        where: params,
        select: {
          company: true,
          createdAt: true,
          email: true,
          id: true,
          message: true,
          name: true,
          phone: true,
          preferredTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
